# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Rockchip RK628 display bridge driver.
#

obj-y				+= rk628.o \
				   rk628_cru.o \
				   rk628_hdmirx.o \
				   rk628_csi.o \
				   rk628_dsi.o \
				   rk628_combrxphy.o \
				   rk628_combtxphy.o

obj-$(CONFIG_V4L2_FWNODE)	+= rk628_csi_v4l2.o \
				   rk628_bt1120_v4l2.o
