
obj-$(CONFIG_CAN_MCP251XFD)   += mcp25xxfd.o

mcp25xxfd-objs := mcp25xxfd-core.o
mcp25xxfd-objs += mcp25xxfd-crc16.o
mcp25xxfd-objs += mcp25xxfd-regmap.o
mcp25xxfd-objs += mcp25xxfd-dump.o
#mcp25xxfd-objs += mcp25xxfd-log.o